#############################################################################
# Makefile for building: Goal_Compute_Testing
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ../Goal_Compute_Testing/Goal_Compute_Testing.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile ../Goal_Compute_Testing/Goal_Compute_Testing.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../Goal_Compute_Testing -I. -I../Goal_Compute_Testing/DriveManager -I../Goal_Compute_Testing/mqtt -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Goal_Compute_Testing1.0.0
DISTDIR = /home/ramesh/build-Goal_Compute_Testing-Desktop-Debug/.tmp/Goal_Compute_Testing1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Goal_Compute_Testing/DriveManager/drivemanagermodule.cpp \
		../Goal_Compute_Testing/DriveManager/drivemanagerthread.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_client_p.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_client.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_frame.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_message.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_network.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_router.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_socket.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_timer.cpp \
		../Goal_Compute_Testing/main.cpp \
		../Goal_Compute_Testing/mainwindow.cpp moc_drivemanagermodule.cpp \
		moc_drivemanagerthread.cpp \
		moc_qmqtt_client.cpp \
		moc_qmqtt_routesubscription.cpp \
		moc_qmqtt_router.cpp \
		moc_qmqtt_networkinterface.cpp \
		moc_qmqtt_socketinterface.cpp \
		moc_qmqtt_timerinterface.cpp \
		moc_qmqtt_network_p.cpp \
		moc_qmqtt_socket_p.cpp \
		moc_qmqtt_timer_p.cpp \
		moc_mainwindow.cpp
OBJECTS       = drivemanagermodule.o \
		drivemanagerthread.o \
		qmqtt_client_p.o \
		qmqtt_client.o \
		qmqtt_frame.o \
		qmqtt_message.o \
		qmqtt_network.o \
		qmqtt_routesubscription.o \
		qmqtt_router.o \
		qmqtt_socket.o \
		qmqtt_timer.o \
		main.o \
		mainwindow.o \
		moc_drivemanagermodule.o \
		moc_drivemanagerthread.o \
		moc_qmqtt_client.o \
		moc_qmqtt_routesubscription.o \
		moc_qmqtt_router.o \
		moc_qmqtt_networkinterface.o \
		moc_qmqtt_socketinterface.o \
		moc_qmqtt_timerinterface.o \
		moc_qmqtt_network_p.o \
		moc_qmqtt_socket_p.o \
		moc_qmqtt_timer_p.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../Goal_Compute_Testing/DriveManager/DriveManager.pri \
		../Goal_Compute_Testing/mqtt/qmqtt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../Goal_Compute_Testing/Goal_Compute_Testing.pro ../Goal_Compute_Testing/DriveManager/drivemanagermodule.h \
		../Goal_Compute_Testing/DriveManager/drivemanagerthread.h \
		../Goal_Compute_Testing/mqtt/qmqtt_client.h \
		../Goal_Compute_Testing/mqtt/qmqtt_frame.h \
		../Goal_Compute_Testing/mqtt/qmqtt_message.h \
		../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.h \
		../Goal_Compute_Testing/mqtt/qmqtt_routedmessage.h \
		../Goal_Compute_Testing/mqtt/qmqtt_router.h \
		../Goal_Compute_Testing/mqtt/qmqtt_networkinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_socketinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_timerinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_client_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_message_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_network_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_socket_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_timer_p.h \
		../Goal_Compute_Testing/mainwindow.h ../Goal_Compute_Testing/DriveManager/drivemanagermodule.cpp \
		../Goal_Compute_Testing/DriveManager/drivemanagerthread.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_client_p.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_client.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_frame.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_message.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_network.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_router.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_socket.cpp \
		../Goal_Compute_Testing/mqtt/qmqtt_timer.cpp \
		../Goal_Compute_Testing/main.cpp \
		../Goal_Compute_Testing/mainwindow.cpp
QMAKE_TARGET  = Goal_Compute_Testing
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Goal_Compute_Testing


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Goal_Compute_Testing/Goal_Compute_Testing.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		../Goal_Compute_Testing/DriveManager/DriveManager.pri \
		../Goal_Compute_Testing/mqtt/qmqtt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../Goal_Compute_Testing/Goal_Compute_Testing.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile ../Goal_Compute_Testing/Goal_Compute_Testing.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
../Goal_Compute_Testing/DriveManager/DriveManager.pri:
../Goal_Compute_Testing/mqtt/qmqtt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
../Goal_Compute_Testing/Goal_Compute_Testing.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile ../Goal_Compute_Testing/Goal_Compute_Testing.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Goal_Compute_Testing/DriveManager/drivemanagermodule.h ../Goal_Compute_Testing/DriveManager/drivemanagerthread.h ../Goal_Compute_Testing/mqtt/qmqtt_client.h ../Goal_Compute_Testing/mqtt/qmqtt_frame.h ../Goal_Compute_Testing/mqtt/qmqtt_message.h ../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.h ../Goal_Compute_Testing/mqtt/qmqtt_routedmessage.h ../Goal_Compute_Testing/mqtt/qmqtt_router.h ../Goal_Compute_Testing/mqtt/qmqtt_networkinterface.h ../Goal_Compute_Testing/mqtt/qmqtt_socketinterface.h ../Goal_Compute_Testing/mqtt/qmqtt_timerinterface.h ../Goal_Compute_Testing/mqtt/qmqtt_client_p.h ../Goal_Compute_Testing/mqtt/qmqtt_message_p.h ../Goal_Compute_Testing/mqtt/qmqtt_network_p.h ../Goal_Compute_Testing/mqtt/qmqtt_socket_p.h ../Goal_Compute_Testing/mqtt/qmqtt_timer_p.h ../Goal_Compute_Testing/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Goal_Compute_Testing/DriveManager/drivemanagermodule.cpp ../Goal_Compute_Testing/DriveManager/drivemanagerthread.cpp ../Goal_Compute_Testing/mqtt/qmqtt_client_p.cpp ../Goal_Compute_Testing/mqtt/qmqtt_client.cpp ../Goal_Compute_Testing/mqtt/qmqtt_frame.cpp ../Goal_Compute_Testing/mqtt/qmqtt_message.cpp ../Goal_Compute_Testing/mqtt/qmqtt_network.cpp ../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.cpp ../Goal_Compute_Testing/mqtt/qmqtt_router.cpp ../Goal_Compute_Testing/mqtt/qmqtt_socket.cpp ../Goal_Compute_Testing/mqtt/qmqtt_timer.cpp ../Goal_Compute_Testing/main.cpp ../Goal_Compute_Testing/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Goal_Compute_Testing/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_drivemanagermodule.cpp moc_drivemanagerthread.cpp moc_qmqtt_client.cpp moc_qmqtt_routesubscription.cpp moc_qmqtt_router.cpp moc_qmqtt_networkinterface.cpp moc_qmqtt_socketinterface.cpp moc_qmqtt_timerinterface.cpp moc_qmqtt_network_p.cpp moc_qmqtt_socket_p.cpp moc_qmqtt_timer_p.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_drivemanagermodule.cpp moc_drivemanagerthread.cpp moc_qmqtt_client.cpp moc_qmqtt_routesubscription.cpp moc_qmqtt_router.cpp moc_qmqtt_networkinterface.cpp moc_qmqtt_socketinterface.cpp moc_qmqtt_timerinterface.cpp moc_qmqtt_network_p.cpp moc_qmqtt_socket_p.cpp moc_qmqtt_timer_p.cpp moc_mainwindow.cpp
moc_drivemanagermodule.cpp: ../Goal_Compute_Testing/DriveManager/drivemanagerthread.h \
		../Goal_Compute_Testing/DriveManager/drivemanagermodule.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/DriveManager/drivemanagermodule.h -o moc_drivemanagermodule.cpp

moc_drivemanagerthread.cpp: ../Goal_Compute_Testing/DriveManager/drivemanagerthread.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/DriveManager/drivemanagerthread.h -o moc_drivemanagerthread.cpp

moc_qmqtt_client.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_client.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_client.h -o moc_qmqtt_client.cpp

moc_qmqtt_routesubscription.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.h -o moc_qmqtt_routesubscription.cpp

moc_qmqtt_router.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_router.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_router.h -o moc_qmqtt_router.cpp

moc_qmqtt_networkinterface.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_networkinterface.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_networkinterface.h -o moc_qmqtt_networkinterface.cpp

moc_qmqtt_socketinterface.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_socketinterface.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_socketinterface.h -o moc_qmqtt_socketinterface.cpp

moc_qmqtt_timerinterface.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_timerinterface.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_timerinterface.h -o moc_qmqtt_timerinterface.cpp

moc_qmqtt_network_p.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_networkinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_network_p.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_network_p.h -o moc_qmqtt_network_p.cpp

moc_qmqtt_socket_p.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_socketinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_socket_p.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_socket_p.h -o moc_qmqtt_socket_p.cpp

moc_qmqtt_timer_p.cpp: ../Goal_Compute_Testing/mqtt/qmqtt_timerinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_timer_p.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mqtt/qmqtt_timer_p.h -o moc_qmqtt_timer_p.cpp

moc_mainwindow.cpp: ../Goal_Compute_Testing/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ramesh/Goal_Compute_Testing -I/home/ramesh/Goal_Compute_Testing/DriveManager -I/home/ramesh/Goal_Compute_Testing/mqtt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Goal_Compute_Testing/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../Goal_Compute_Testing/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Goal_Compute_Testing/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

drivemanagermodule.o: ../Goal_Compute_Testing/DriveManager/drivemanagermodule.cpp ../Goal_Compute_Testing/DriveManager/drivemanagermodule.h \
		../Goal_Compute_Testing/DriveManager/drivemanagerthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drivemanagermodule.o ../Goal_Compute_Testing/DriveManager/drivemanagermodule.cpp

drivemanagerthread.o: ../Goal_Compute_Testing/DriveManager/drivemanagerthread.cpp ../Goal_Compute_Testing/DriveManager/drivemanagerthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drivemanagerthread.o ../Goal_Compute_Testing/DriveManager/drivemanagerthread.cpp

qmqtt_client_p.o: ../Goal_Compute_Testing/mqtt/qmqtt_client_p.cpp ../Goal_Compute_Testing/mqtt/qmqtt_client_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_client.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_network_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_networkinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_frame.h \
		../Goal_Compute_Testing/mqtt/qmqtt_message.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_client_p.o ../Goal_Compute_Testing/mqtt/qmqtt_client_p.cpp

qmqtt_client.o: ../Goal_Compute_Testing/mqtt/qmqtt_client.cpp ../Goal_Compute_Testing/mqtt/qmqtt_client.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_client_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_client.o ../Goal_Compute_Testing/mqtt/qmqtt_client.cpp

qmqtt_frame.o: ../Goal_Compute_Testing/mqtt/qmqtt_frame.cpp ../Goal_Compute_Testing/mqtt/qmqtt_frame.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_frame.o ../Goal_Compute_Testing/mqtt/qmqtt_frame.cpp

qmqtt_message.o: ../Goal_Compute_Testing/mqtt/qmqtt_message.cpp ../Goal_Compute_Testing/mqtt/qmqtt_message.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_message_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_message.o ../Goal_Compute_Testing/mqtt/qmqtt_message.cpp

qmqtt_network.o: ../Goal_Compute_Testing/mqtt/qmqtt_network.cpp ../Goal_Compute_Testing/mqtt/qmqtt_network_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_networkinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_socket_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_socketinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_ssl_socket_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_timer_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_timerinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_websocket_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_websocketiodevice_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_network.o ../Goal_Compute_Testing/mqtt/qmqtt_network.cpp

qmqtt_routesubscription.o: ../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.cpp ../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_router.h \
		../Goal_Compute_Testing/mqtt/qmqtt_client.h \
		../Goal_Compute_Testing/mqtt/qmqtt_routedmessage.h \
		../Goal_Compute_Testing/mqtt/qmqtt_message.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_routesubscription.o ../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.cpp

qmqtt_router.o: ../Goal_Compute_Testing/mqtt/qmqtt_router.cpp ../Goal_Compute_Testing/mqtt/qmqtt_router.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h \
		../Goal_Compute_Testing/mqtt/qmqtt_client.h \
		../Goal_Compute_Testing/mqtt/qmqtt_routesubscription.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_router.o ../Goal_Compute_Testing/mqtt/qmqtt_router.cpp

qmqtt_socket.o: ../Goal_Compute_Testing/mqtt/qmqtt_socket.cpp ../Goal_Compute_Testing/mqtt/qmqtt_socket_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_socketinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_socket.o ../Goal_Compute_Testing/mqtt/qmqtt_socket.cpp

qmqtt_timer.o: ../Goal_Compute_Testing/mqtt/qmqtt_timer.cpp ../Goal_Compute_Testing/mqtt/qmqtt_timer_p.h \
		../Goal_Compute_Testing/mqtt/qmqtt_timerinterface.h \
		../Goal_Compute_Testing/mqtt/qmqtt_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmqtt_timer.o ../Goal_Compute_Testing/mqtt/qmqtt_timer.cpp

main.o: ../Goal_Compute_Testing/main.cpp ../Goal_Compute_Testing/mainwindow.h \
		../Goal_Compute_Testing/DriveManager/drivemanagermodule.h \
		../Goal_Compute_Testing/DriveManager/drivemanagerthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Goal_Compute_Testing/main.cpp

mainwindow.o: ../Goal_Compute_Testing/mainwindow.cpp ../Goal_Compute_Testing/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Goal_Compute_Testing/mainwindow.cpp

moc_drivemanagermodule.o: moc_drivemanagermodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drivemanagermodule.o moc_drivemanagermodule.cpp

moc_drivemanagerthread.o: moc_drivemanagerthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drivemanagerthread.o moc_drivemanagerthread.cpp

moc_qmqtt_client.o: moc_qmqtt_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_client.o moc_qmqtt_client.cpp

moc_qmqtt_routesubscription.o: moc_qmqtt_routesubscription.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_routesubscription.o moc_qmqtt_routesubscription.cpp

moc_qmqtt_router.o: moc_qmqtt_router.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_router.o moc_qmqtt_router.cpp

moc_qmqtt_networkinterface.o: moc_qmqtt_networkinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_networkinterface.o moc_qmqtt_networkinterface.cpp

moc_qmqtt_socketinterface.o: moc_qmqtt_socketinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_socketinterface.o moc_qmqtt_socketinterface.cpp

moc_qmqtt_timerinterface.o: moc_qmqtt_timerinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_timerinterface.o moc_qmqtt_timerinterface.cpp

moc_qmqtt_network_p.o: moc_qmqtt_network_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_network_p.o moc_qmqtt_network_p.cpp

moc_qmqtt_socket_p.o: moc_qmqtt_socket_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_socket_p.o moc_qmqtt_socket_p.cpp

moc_qmqtt_timer_p.o: moc_qmqtt_timer_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmqtt_timer_p.o moc_qmqtt_timer_p.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Goal_Compute_Testing/bin || mkdir -p $(INSTALL_ROOT)/opt/Goal_Compute_Testing/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Goal_Compute_Testing/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Goal_Compute_Testing/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Goal_Compute_Testing/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

